FROM pretix/standalone:stable
USER root
RUN pip3 install pretix-cashpayment
RUN pip3 install pretix-zugferd
RUN pip3 install pretix-oidc
RUN pip3 install pretix-fontpack-free
RUN pip3 install pretix-passbook
USER pretixuser
WORKDIR /pretix/src
RUN make production