on:
  push:
    paths:
      - dockerfile.pretix
  workflow_dispatch:
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: qemu-setup
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - id: setup-docker-buildx
        name: Setup BuildX for Docker
        uses: docker/setup-buildx-action@v3

      - id: registry-login
        name: Login into Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username:  ${{ github.actor }}
          password: ${{secrets.GITHUB_TOKEN}}


      - id: docker-metadata
        name: Configure Metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/unikino-gegenlicht/pretix
          tags: |
            type=raw,value=latest

      - id: build-and-push
        uses: docker/build-push-action@v5
        with:
          file: dockerfile.pretix
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}